SET SERVEROUTPUT ON
SET VERIFY OFF
DECLARE
    TYPE T_EMP_REC IS RECORD (
        V_JOBID EMPLOYEE.JOB_ID%TYPE,
        V_MAXSALARY EMPLOYEE.SALARY%TYPE
    );
    TYPE TEmpList IS TABLE OF T_EMP_REC;
    V_EMPLIST TEmpList;
BEGIN
    SELECT JOB_ID, MAX(SALARY) 
    BULK COLLECT INTO V_EMPLIST 
    FROM EMPLOYEE 
    GROUP BY JOB_ID;

    DBMS_OUTPUT.PUT_LINE('==========================');
    DBMS_OUTPUT.PUT_LINE('Job ID        Max Salary');
    DBMS_OUTPUT.PUT_LINE('==========================');

    FOR I IN V_EMPLIST.FIRST .. V_EMPLIST.LAST LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(V_EMPLIST(I).V_JOBID,15,' ') || RPAD(V_EMPLIST(I).V_MAXSALARY,15,' '));
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('==========================');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
