SET SERVEROUTPUT ON
SET VERIFY OFF
ACCEPT S_CUSTID PROMPT 'Enter the Customer ID'
DECLARE
V_CUSTID CUSTOMER.CUSTOMER_ID%TYPE;
V_NAME CUSTOMER.NAME%TYPE;
V_ADDRESS CUSTOMER.ADDRESS%TYPE;
V_CITY CUSTOMER.CITY%TYPE;
V_CREDITLIMIT CUSTOMER.CREDIT_LIMIT%TYPE;
V_AREACODE CUSTOMER.AREA_CODE%TYPE;
V_NEWCREDITLIMIT NUMBER;
V_CHANGE NUMBER;


BEGIN
    V_CUSTID:='&S_CUSTID';
    SELECT CUSTOMER_ID, NAME, ADDRESS, CITY, CREDIT_LIMIT, AREA_CODE
    INTO V_CUSTID, V_NAME, V_ADDRESS, V_CITY, V_CREDITLIMIT, V_AREACODE
    FROM CUSTOMER
    WHERE CUSTOMER_ID = V_CUSTID;

    CASE
        WHEN V_AREACODE <= 400 THEN V_CHANGE := 0.04;
        WHEN V_AREACODE > 400 AND V_AREACODE <= 600 THEN V_CHANGE := -0.03;
        WHEN V_AREACODE > 600 THEN V_CHANGE := 0.02;
    END CASE;

    
    V_NEWCREDITLIMIT:=(V_CREDITLIMIT*V_CHANGE)+V_CREDITLIMIT;


    DBMS_OUTPUT.PUT_LINE('=======================================================================');
    DBMS_OUTPUT.PUT_LINE(RPAD('Customer ID: ', 55, ' ') || V_CUSTID);
    DBMS_OUTPUT.PUT_LINE(RPAD('Name: ', 55, ' ') || V_NAME);
    DBMS_OUTPUT.PUT_LINE(RPAD('Address: ', 55, ' ') || V_ADDRESS);
    DBMS_OUTPUT.PUT_LINE(RPAD('City: ', 55, ' ') || V_CITY); 
    DBMS_OUTPUT.PUT_LINE(RPAD('Previous credit limit: ', 55, ' ') || V_CREDITLIMIT);
    DBMS_OUTPUT.PUT_LINE(RPAD('New credit limit: ', 55, ' ') || V_NEWCREDITLIMIT);
    DBMS_OUTPUT.PUT_LINE(RPAD('Percentage of increase or decrease of credit limit: ', 55, ' ') || V_CHANGE*100 || '%');
    DBMS_OUTPUT.PUT_LINE('======================================================================');



EXCEPTION
WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('THE CUSTOMER ' || V_CUSTID || ' DOES NOT EXIST');
END;